# Generated by Django 2.2.13 on 2020-06-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('active', 'Active'), ('deleted', 'Deleted'), ('time out', 'Time Out'), ('completed', 'Completed'), ('cancel', 'Cancel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('active', 'Active'), ('deleted', 'Deleted'), ('blocked', 'Blocked'), ('completed', 'Completed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='eventjobcategorylinking',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('active', 'Active'), ('deleted', 'Deleted'), ('blocked', 'Blocked'), ('completed', 'Completed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='attend_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('attending', 'Attending'), ('completed', 'Completed'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('active', 'Active'), ('deleted', 'Deleted'), ('blocked', 'Blocked'), ('completed', 'Completed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='eventuserwishlist',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('active', 'Active'), ('deleted', 'Deleted'), ('blocked', 'Blocked'), ('completed', 'Completed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usercoin',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('active', 'Active'), ('deleted', 'Deleted'), ('blocked', 'Blocked'), ('completed', 'Completed')], max_length=10),
        ),
    ]
