# Generated by Django 3.0.7 on 2020-06-23 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_eventimage_eventjobcategorylinking_eventmember_eventnotofication_eventnotoficationhistory_eventuserw'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='eventuserwishlist',
            unique_together={('event', 'user')},
        ),
    ]
