# Generated by Django 3.0.7 on 2020-06-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200624_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='attend_status',
            field=models.CharField(choices=[('attend', 'Attend'), ('absense', 'Absense'), ('completed', 'Completed')], max_length=10),
        ),
    ]
