# Generated by Django 2.2.13 on 2020-06-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200624_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventnotofication',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='eventnotofication',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventnotofication',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='eventnotoficationhistory',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='eventnotoficationhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='event_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='notification',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
        migrations.DeleteModel(
            name='EventNotofication',
        ),
        migrations.DeleteModel(
            name='EventNotoficationHistory',
        ),
    ]
